apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "otdsws.name" . }}-configmap

data:
  COUNTER: '{{ .Values.global.counter }}'
  OTDS_JAKARTA_PERSISTENCE_JDBC_USER: {{ .Values.otdsdb.username }}
  OTDS_JAKARTA_PERSISTENCE_JDBC_URL: {{ template "otdsws.dburl" . }}
{{- if eq .Values.migration.enabled true }}
  OTDS_MIGRATE: "true"
{{- if eq .Values.migration.usingLegacyImage true }}
  LEGACY_OPENDJ: "true"
{{- else }}
{{- if .Values.migration.opendjUri }}
  OTDS_DIRECTORY_BOOTSTRAP_SERVERLIST: {{ .Values.migration.opendjUri }}
{{- else }}
  OTDS_DIRECTORY_BOOTSTRAP_SERVERLIST: {{ printf "ldap://%s" .Values.migration.serviceName }}:{{ .Values.migration.servicePort }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.additionalJavaOpts }}
  CATALINA_OPTS: {{ .Values.additionalJavaOpts }}
{{- end }}
{{- if .Values.jvmMemory }}
  JVM_MEMORY: {{ .Values.jvmMemory }}
{{- else }}
{{- if eq .Values.resources.enabled true }}
{{- if .Values.resources.limits.memory }}
  JVM_MEMORY: {{ .Values.resources.limits.memory }}
  JVM_MEMORY_DETECTED: "true"
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.ingress.prependPath }}
  APP_PATH: {{ .Values.ingress.prependPath }}
{{- end }}
{{- if eq .Values.carrierGradeNAT true }}
  CARRIER_GRADE_NAT: "true"
{{- end }}
  SAPSYSTEMCLIENT: "001"
  SAPSYSTEMNAME: OTX
{{- if .Values.global.timeZone }}
  TZ: {{ .Values.global.timeZone }}
{{- end -}}
{{- if .Values.newrelic.NEW_RELIC_LICENSE_KEY }}
{{ toYaml .Values.newrelic | indent 2 }}
{{- end }}
---
