#Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
   {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: "http" 
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}