apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "base.resource.name" . }}-configmap
data:
    AUTH_TOKEN_URL: {{ template "otds.api.url" .}}/oauth2/token
    DOC_ROOT: 'https://developer.opentext.com/products_services/aa064dbd-8954-4d0f-8892-65fe2de124bb'
    {{ template "node.forwarding" . }}
    LOG_LEVEL: '{{ .Values.loglevel }}'
{{- if (include "is.iv" .) }}
    ARTIFACT_BASE_URL_PUBLIC: {{ $.Values.global.publicWebProtocol }}://otiv-asset{{ include "ingress.suffix" .}}/artifacts
    ARTIFACT_BASE_URL: http://otiv-asset/artifacts
    PUBLICATION_AUTHORITY: http://otiv-publication:{{ .Values.publication.port }}
{{- else }}
    PUBLICATION_AUTHORITY: http://cvt-publication:{{ .Values.publication.port }}
{{- end }}
    CORS_ADDITIONAL_HEADERS_LIST: '{{ .Values.global.customHttpHeaders }}'
    COUNTER: '{{ .Values.global.counter }}'
    {{ template "cors.config" . }}
    {{ template "forwarded.config" . }}
    {{- template "new.relic.viewing.config" . }}
{{- if .Values.nodeOptions }}
    NODE_OPTIONS: '{{ .Values.nodeOptions }}'
{{- end }}
    OTDS_CERT_UPDATE_INTERVAL: '{{ .Values.global.otdsCertUpdateInterval }}'
    OTDS_ORIGIN: {{ template "otds.api.url" .}}
    {{- template "proxy.url.params" . }}
    PORT: '{{ .Values.service.targetPort }}'
    SEARCH_AUTHORITY: {{ $.Values.global.publicWebProtocol }}://{{ include "ingress.fqdn" .}}
    {{- template "timezone" . }}
    __VERSION__: '{{ template "version.stamp" . }}'
