dctm-server:
  db:
    database:
      replicaCount: 1
    alterParam:
      max_connections: 1000
      shared_buffers: 2GB
    persistentVolume:
      size: 100Gi
    resources:
      limits:
        cpu: 4000m
        memory: 16Gi
      requests:
        cpu: 2000m
        memory: 8Gi
  docbroker:
    docbroker:
      replicaCount: 1
    persistentVolume:
      size: 1Gi
    resources:
      limits:
        cpu: 600m
        memory: 600Mi
      requests:
        cpu: 300m
        memory: 300Mi
  content-server:
    contentserver:
      replicaCount: 1
      docbrokersCount: 1
    volumeClaimTemplate:
      size: 1Gi
    persistentVolume:
      size: 400Gi
    resources:
      limits:
        cpu: 4000m
        memory: 20Gi
      requests:
        cpu: 800m
        memory: 12Gi
  dctm-rest:
    replicaCount: 1
    resources:
      limits:
        cpu: 1500m
        memory: 4Gi
      requests:
        cpu: 800m
        memory: 2Gi
  dctm-cmis:
    replicaCount: 1
  dctm-workflow-designer:
    replicaCount: 1
    persistentVolume:
      size: 2Gi
    volumeClaimTemplates:
      size: 200Mi
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 3Gi
  contentconnect:
    replicaCount: 1
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1
        memory: 2Gi
    contentconnectdb:
      replicaCount: 1
      resources:
        limits:
          cpu: 0.5
          memory: 600Mi
        requests:
          cpu: 0.4
          memory: 500Mi   
  dtrbase:
    persistentVolumeClaim:
      size: 1Gi
    deployment:
      replicaCount: 1
  da:
    replicaCount: 1
    persistentVolumeClaim:
      size: 1Gi
    resources:
      limits:
        cpu: 400m
        memory: 4Gi
      requests:
        cpu: 200m
        memory: 2Gi
  records:
    records:
      replicaCount: 1
    resources:
      limits:
        cpu: 800m
        memory: 4Gi
      requests:
        cpu: 400m
        memory: 2Gi
  rqm:
    containers:
      rqm:
        replicaCount: 1
    resources:
      limits:
        cpu: 800m
        memory: 4Gi
      requests:
        cpu: 400m
        memory: 2Gi
d2classic:
  replicaCount: 1
  graylog:
    volumeClaimTemplate:
      logVctSize: 2Gi
  persistentVolume:
    size: 1Gi
  resources:
    limits:
     cpu: 800m
     memory: 4Gi
    requests:
     cpu: 300m
     memory: 2.5Gi
d2config:
  replicaCount: 1
  graylog:
    volumeClaimTemplate:
      logVctSize: 2Gi
  persistentVolume:
    size: 1Gi
  extension:
    PVCSize: 8Gi
  resources:
    limits:
     cpu: 400m
     memory: 8Gi
    requests:
     cpu: 200m
     memory: 4Gi
d2smartview:
  replicaCount: 1
  graylog:
    volumeClaimTemplate:
      logVctSize: 2Gi
  persistentVolume:
    size: 1Gi
  resources:
    limits:
     cpu: 800m
     memory: 4Gi
    requests:
     cpu: 300m
     memory: 2.5Gi
d2rest:
  replicaCount: 1
  graylog:
    volumeClaimTemplate:
      logVctSize: 2Gi
  persistentVolume:
    size: 1Gi
  resources:
    limits:
     cpu: 400m
     memory: 4Gi
    requests:
     cpu: 200m
     memory: 2Gi
documentum-search:    
  zookeeper:
    replicaCount: 2
    resources:
       requests:
         cpu: 100m
         memory: 1Gi
       limits:
         cpu: 300m
         memory: 1Gi
    persistence:
      size: 1Gi
  kafka:
    replicaCount: 2
    resources:
       requests:
         cpu: 500m
         memory: 1Gi
       limits:
         cpu: 1500m
         memory: 3Gi
    persistence:
      size: 9Gi
  solr:
    replicaCount: 2
    resources:
       requests:
         cpu: 1000m
         memory: 6Gi
       limits:
         cpu: 3000m
         memory: 10Gi
    volumeClaimTemplates:
      storageSize: 29Gi
  parser:
    replicaCount: 1
    resources:
       requests:
         cpu: 1000m
         memory: 3Gi
       limits:
         cpu: 3000m
         memory: 5Gi
  indexer:
    replicaCount: 1
    resources:
       requests:
         cpu: 500m
         memory: 1Gi
       limits:
         cpu: 1500m
         memory: 3Gi
  coresearch:
    replicaCount: 1
    resources:
       requests:
         cpu: 500m
         memory: 3Gi
       limits:
         cpu: 1500m
         memory: 5Gi
  agent:
    replicaCount: 1
    resources:
       requests:
         cpu: 1000m
         memory: 3Gi
       limits:
         cpu: 3000m
         memory: 5Gi
  fetcher:
    replicaCount: 1
    resources:
       requests:
         cpu: 400m
         memory: 1Gi
       limits:
         cpu: 600m
         memory: 3Gi
  admin:
    replicaCount: 1
    resources:
       requests:
         cpu: 400m
         memory: 1Gi
       limits:
         cpu: 600m
         memory: 3Gi
xplore:
  cps:
    replicaCount: 2
  persistentVolume:
    size: 100Gi
  resources:
    indexserver:
      limits:
        cpu: 1000m
        memory: 12Gi
      requests:
        cpu: 500m
        memory: 6Gi
    indexagent:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
    cps:
      limits:
        cpu: 1000m
        memory: 12Gi
      requests:
        cpu: 500m
        memory: 6Gi
