
### xPlore CPS ###
cps:
  replicaCount: 2
persistentVolume:
  size: 1140Gi
### Resources ###
resources:
  indexserver:
    requests:
      memory: 8Gi
      cpu: 500m
    limits:
      memory: 8Gi
      cpu: 500m
  indexagent:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 500m
  cps:
    requests:
      memory: 6Gi
      cpu: 1000m
    limits:
      memory: 6Gi
      cpu: 1000m