
### xPlore CPS ###
cps:
  replicaCount: 2
persistentVolume:
  size: 1900Gi
### Resources ###
resources:
  indexserver:
    requests:
      memory: 12Gi
      cpu: 1000m
    limits:
      memory: 12Gi
      cpu: 1000m
  indexagent:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m
  cps:
    requests:
      memory: 6Gi
      cpu: 1000m
    limits:
      memory: 6Gi
      cpu: 1000m