apiVersion: v2
appVersion: "23.4"
dependencies:
- condition: cs-secrets.enabled
  name: cs-secrets
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: db.enabled
  name: db
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "15.2"
- condition: cs-logging-configMap.enabled
  name: cs-logging-configMap
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: docbroker.enabled
  name: docbroker
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: content-server.enabled
  name: content-server
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: dctm-ingress.enabled
  name: dctm-ingress
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: cs-dfc-properties.enabled
  name: cs-dfc-properties
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: dtrbase.enabled
  name: dtrbase
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: 22.4.2
- condition: dctm-rest.enabled
  name: dctm-rest
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: dctm-cmis.enabled
  name: dctm-cmis
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: dctm-workflow-designer.enabled
  name: dctm-workflow-designer
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: contentconnect.enabled
  name: contentconnect
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: da.enabled
  name: da
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: dfs.enabled
  name: dfs
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: records.enabled
  name: records
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: rqm.enabled
  name: rqm
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.4"
- condition: otds.enabled
  name: otds
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: 23.3.0
- condition: dctm-dcc.enabled
  name: dctm-dcc
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "22.4"
description: Content server Helm chart for Kubernetes
name: dctm-server
version: "23.4"
