{{- if or (not .Values.rabbitmq.existingErlangSecret) (not .Values.global.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if not .Values.global.existingSecret }}{{ if .Values.global.amqp.password }}
  rabbitmq-password: {{ .Values.global.amqp.password | b64enc | quote }}
  {{ end }}{{ end }}
  {{ if not .Values.rabbitmq.existingErlangSecret }}{{ if .Values.rabbitmq.erlangCookie }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}
  {{ else }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}{{ end }}
{{- end }}
{{- range $key, $value := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  labels:
    app: {{ template "rabbitmq.name" $ }}
    chart: {{ template "rabbitmq.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
{{ $value | toYaml | nindent 2 }}
{{- end }}
