apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "base.resource.name" . }}-configmap
data:
    {{ template "cors.config" . }}
    {{ template "forwarded.config" . }}
    CORS_ADDITIONAL_HEADERS_LIST: '{{ .Values.global.customHttpHeaders }}'
    COUNTER: '{{ .Values.global.counter }}'
    DB_PROVIDER: {{ .Values.global.database.type }}
    DB_HOST: {{ .Values.global.database.hostname }}
    DB_PORT: '{{ .Values.global.database.port }}'
    DB_NAME: {{ eq .Values.global.database.type "postgresql" | ternary .Values.global.database.ivName .Values.global.database.adminDatabase }}
{{- if eq .Values.global.database.type "postgresql" }}
    DB_PSQL: {{ .Values.global.database.adminDatabase }}
{{- end }}
{{- if (include "is.iv" .) }}
    DB_USER: {{ .Values.global.database.adminUsername }}
{{- end }}
    DB_USE_SSL: '{{ .Values.global.database.ssl }}'
    DB_MAX_POOL_SIZE: '{{ .Values.dbMaxPoolSize }}'
{{- if .Values.enableRoleBasedAccessControl }}
    ENABLE_ROLE_BASED_ACCESS_CONTROL: '{{ .Values.enableRoleBasedAccessControl }}'
{{- end }}
    DOC_ROOT: 'https://developer.opentext.com/products_services/aa064dbd-8954-4d0f-8892-65fe2de124bb'
    {{ template "node.forwarding" . }}
{{- if .Values.jwtSecret }}
    MARKUP_JWT_SECRET: '{{ .Values.jwtSecret }}'
{{- end }}
    LOG_LEVEL: '{{ .Values.loglevel }}'
    {{- template "new.relic.viewing.config" . }}
    MARKUP_AUTHORITY: {{ $.Values.global.publicWebProtocol }}://{{ include "ingress.fqdn" .}}
    NODE_ENV: production
{{- if .Values.nodeOptions }}
    NODE_OPTIONS: '{{ .Values.nodeOptions }}'
{{- end }}
    OTDS_CERT_UPDATE_INTERVAL: '{{ .Values.global.otdsCertUpdateInterval }}'
    OTDS_ORIGIN: {{ template "otds.api.url" .}}
    PORT: '{{ .Values.service.targetPort }}'
{{- if not (include "is.iv" .) }}
    SUBSCRIPTION_DELETE_INTERVAL: '10'
    SUBSCRIPTION_DELETE_LIMIT: '10000'
{{- end }}
    {{- template "timezone" . }}
    VERTX_CLUSTER_NETWORK_PORT: '{{ .Values.global.hazelport }}'
    __VERSION__: '{{ template "version.stamp" . }}'
