apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}-secret
type: Opaque
data:
####  tomcatPassword: {{ default "" .Values.tomcat.password | b64enc | quote }}	
  superUserPassword: {{ default "" .Values.docbaseConnection.superUserPassword | b64enc | quote }}	
