{{- if .Values.persistentVolume.awsEFS }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.awsEFSCSIPvName }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  csi:
    driver: {{ .Values.persistentVolume.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.persistentVolume.awsEFSCSIHandle }}
{{- end }}