{{- if .Values.trustStore.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}-secret
type: Opaque
data:
  trustStoreFile: |-
    {{ $trustStoreFile := printf "secrets/%s" .Values.trustStore.fileName }}
    {{ .Files.Get $trustStoreFile | b64enc }}
{{- end }}