#Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}
  labels:
    app: {{ .Values.prefix }}
spec:
  type: ClusterIP
  ports:
  - port: {{ default "7000" .Values.adminConsoleServicePort }}
    name: xdaport
    targetPort: 7000
  selector:
    app: {{ .Values.prefix }}