apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  strategy:
   type: {{ .Values.strategyType}}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dctm-rest.custom-labels" . | indent 6 }}
  template:
    metadata:
        labels:
          {{- include "dctm-rest.custom-labels" . | indent 10 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.serviceAccountName }}
      initContainers:
          - name: {{ .Values.restInitContainers.name }}
            image: {{ .Values.restInitContainers.image }}:{{ .Values.restInitContainers.imageTag }}
            imagePullPolicy: {{ .Values.restInitContainers.imagePullPolicy }}
            volumeMounts: 
              {{- if (eq .Values.rest.useCommonPVC true) }}
              - name: common-volume
              {{- else  }}
              - name: custom-script-pvc
              {{- end }}
                mountPath: /home/dmadmin/dctmrestextension
                subPath: dctmrestextension

    {{- if  and (.Values.extraInitContainers) (.Values.custom.useInitContainers) }}
          - name: {{ .Values.extraInitContainers.name }}
            image: {{ .Values.extraInitContainers.image }}:{{ .Values.extraInitContainers.imageTag }}
            imagePullPolicy: {{ .Values.extraInitContainers.imagePullPolicy }}
            volumeMounts:
              - name: custom-script-pvc
                mountPath: /opt/customscriptpvc
                subPath: customscriptpvc
    {{- end }}            


{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
{{ end }}    
      containers:
          # Fluentd Section Starts
          {{ if eq .Values.fluentd_service.enable true }}
          - name: fluentd-sidecar-{{ .Values.serviceName }}
            image: {{ .Values.fluentd_service.image | quote }}
            imagePullPolicy: {{ .Values.fluentd_service.pullPolicy }}
          {{- if .Values.fluentd_service.readiness.enable }} 
            readinessProbe:
              exec: {
                command: [
                  bash,
                    -c,
                    /fluentd-setup/scripts/fluentd_readiness.sh
                ]
              }
              initialDelaySeconds: 10
              periodSeconds: 10
              failureThreshold: 2
              timeoutSeconds: 5
          {{ end }}    
            env:
              - name: KUBERNETES
                value: "true"
              - name: FLUENTD_TCP_PORT
                value: {{ .Values.fluentd_service.TCPPort | quote }}
              - name: FLUENTD_REST_PORT
                value: {{ .Values.fluentd_service.RESTPort | quote }}
              - name: FLUENTD_LOG_FOLDER_PATH
                value: fluentd-logging
              - name: FLUENTD_CONFIG_MAP_PATH
                value: fluentd-config-map
            volumeMounts:
              - mountPath: /fluentd-logging
                name: {{ .Values.fluentd_service.servicedataPVCName }}-logs
              - mountPath: /fluentd-config-map/config_map
                name: fluentdconfig-map
            ports:
              - containerPort: {{ .Values.fluentd_service.TCPPort }}
                name: fluentdtcpport
              - containerPort: {{ .Values.fluentd_service.RESTPort }}
                name: fluentdrestport
          {{ end }}
          # Fluentd Section Ends
          {{- if eq .Values.graylog.enabled true }}
          - name: graylog-sidecar-{{ .Values.serviceName }}
            image: {{ .Values.graylog.image | quote }}
            imagePullPolicy: Always
            env:
              - name: GRAYLOG_SERVER
                value: {{ .Values.graylog.server | quote }}
              - name: GRAYLOG_PORT
                value: {{ .Values.graylog.port | quote }}
              - name: GRAYLOG_SERVICE_TOKEN
                value: {{ .Values.graylog.serviceToken | quote }}
              - name: TAGS
                value: {{ .Values.graylog.tags | quote }}
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: NAMESPACE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            volumeMounts:
              - name: shared-logs
                mountPath: /pod-data    
          {{- end }}    
          - name: {{ .Values.containerName }}
            image: {{ .Values.image }}/{{ .Values.path }}:{{ .Values.imageTag }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            command: ['bin/sh', '-c', 'mkdir -p /home/dmadmin/restextnscriptfolder/;chmod 755 /home/dmadmin/restextnscriptfolder/;cp /home/dmadmin/dctmrestextension/extensionstartup.sh /home/dmadmin/restextnscriptfolder/;chmod +x /home/dmadmin/restextnscriptfolder/extensionstartup.sh;/home/dmadmin/restextnscriptfolder/extensionstartup.sh {{ .Values.java.javaOptions }}']
            env:
              {{- if (.Values.newrelic.enabled) }}
              - name: NEW_RELIC_PROXY_HOST
                value: {{ quote .Values.newrelic.proxy_host }}
              - name: NEW_RELIC_PROXY_PORT
                value: {{ quote .Values.newrelic.proxy_port }}
              - name: NEW_RELIC_PROXY_SCHEME
                value: {{ quote .Values.newrelic.proxy_protocol }}
              {{- if (.Values.content_server.secretName) }}
              - name: NEW_RELIC_LICENSE_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.content_server.secretName }}
                    key: newrelicLicensekey
              {{- end }}
              - name: NEW_RELIC_APP_NAME
                value: {{ quote .Values.newrelic.app_name }}
              - name: NEW_RELIC_FILE
                value: {{ .Values.extraConfigMountPath }}/{{ .Values.newrelic.configurationFile }}
              {{- if (.Values.newrelic.addNodeNamePrefix) }}
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              {{- end }}
              {{- end }}
              {{- if (.Values.content_server.secretName) }}
              - name: BOF_REGISTRY_USER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.content_server.secretName }}
                    key: globalRegistryPassword
              {{- end }}
              - name: KUBERNETES
                value: "true"
              {{ if eq .Values.fluentd_service.enable true }}
              - name: EVENT_HUB_FLUENTD_PORT
                value: {{ .Values.fluentd_service.TCPPort | quote }}
              - name: FLUENTD_SERVICE_ENABLED
                value: {{ .Values.fluentd_service.enable | quote }}
              {{ end }}
              - name: SINGLE_HELM_ENABLED
                value: {{ .Values.single_helm.enable | quote }}
              - name: ACS_HOST
                value: {{ .Values.acsService.serviceName | quote }}
              - name: ACS_PORT
                value: {{ .Values.acsService.servicePort | quote }}
              {{ if eq .Values.log4j.formatMsgNoLookups true }}
              - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
                value: "true"
              {{ end }}
              - name: USE_CUSTOM_INITCONTAINERS
                value: {{ .Values.custom.useInitContainers | quote }}
              {{- if eq .Values.timeZone.enable true }}
              - name: TZ
                value: {{ .Values.timeZone.value }}
              {{- end }}
            volumeMounts:
              - name: rest-config-volume
                mountPath: /home/dmadmin/config
              {{- if (.Values.newrelic.enabled) }}
              - name: ext-conf-volume
                mountPath: {{ .Values.extraConfigMountPath }}
              {{- end}}
              - name: shared-logs
                mountPath: {{ .Values.graylog.logsDir }}
              {{- if .Values.docbroker.useCertificate }}
              - name: dbr-cert-volume
                mountPath: /home/dmadmin/dbr-cert
                subPath: {{ .Values.docbroker.pvcCertSubPath }}
              {{- end }}
              {{- if (eq .Values.custom.useInitContainers true) }}
              - name: custom-script-pvc
                mountPath: /opt/customscriptpvc
                subPath: customscriptpvc
              {{- end }}
              {{- if (eq .Values.rest.useCommonPVC true) }}
              - name: common-volume
                mountPath: /home/dmadmin/dctmrestextension
                subPath: dctmrestextension
              {{- end }}
              {{- if or ( eq .Values.rest.useCommonPVC false ) (and (eq .Values.custom.useInitContainers false) ( eq .Values.rest.useCommonPVC false )) }}
              - name: custom-script-pvc
                mountPath: /home/dmadmin/dctmrestextension
                subPath: dctmrestextension
              {{- end }}
              {{- if eq .Values.timeZone.enable true }}
              - name: zoneinfo
                mountPath: /etc/localtime
                subPath: {{ .Values.timeZone.value }}
                readOnly: true
              {{- end }}
            resources:
              requests:
                memory: {{ .Values.resources.requests.memory | quote }}
                cpu: {{ .Values.resources.requests.cpu | quote }}
              limits:
                memory: {{ .Values.resources.limits.memory | quote }}
                cpu: {{ .Values.resources.limits.cpu | quote }}
            readinessProbe:
              httpGet:
                path: /dctm-rest/repositories
                port: {{ .Values.httpPort }}
              initialDelaySeconds: 40
              periodSeconds: 15
              timeoutSeconds: 10
            {{- if (.Values.livenessProbe.enabled) }}
            livenessProbe:
              httpGet:
                scheme: {{ .Values.livenessProbe.scheme }}
                path: {{ .Values.livenessProbe.probeUrl }}
                {{- if eq .Values.livenessProbe.scheme "HTTP"}}
                port: {{ .Values.httpPort }}
                {{- end }}
                {{- if eq .Values.livenessProbe.scheme "HTTPS"}}
                port: {{ .Values.httpsPort }}
                {{- end }}
              initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
              timeoutSeconds: 10
            {{- end }}
      volumes:
        - name: rest-config-volume
          projected:
            sources:
            - configMap:
                name: {{ .Values.serviceName }}-configmap
            - configMap:
                name: {{ .Values.serviceName }}-logging-configmap
            - configMap:
                name: {{ .Values.serviceName }}-rest-api-runtime-properties
            {{- if (.Values.existingConfigMap) }}
            - configMap:
                name: {{ .Values.existingConfigMap }}
            {{- end }}
        - name: shared-logs
          emptyDir: {}
        {{- if (eq .Values.rest.useCommonPVC true) }}
        - name: common-volume
          persistentVolumeClaim:
            claimName: {{ .Values.rest.commonPVCname }}
        {{- end }}
        {{- if or ( eq .Values.custom.useInitContainers true ) ( eq .Values.rest.useCommonPVC false )  }}
        - name: custom-script-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.custom.scriptPVCname }}
        {{- end }}
        {{- if .Values.docbroker.useCertificate }}
        - name: dbr-cert-volume
          persistentVolumeClaim:
            claimName: {{ .Values.docbroker.dbrServiceName }}-pvc
        {{- end }}
        {{if (.Values.newrelic.enabled) }}
        - name: ext-conf-volume
          configMap:
            name: {{ .Values.serviceName }}-configmap-ext
        {{- end }}
        {{- if eq .Values.fluentd_service.enable true }}
        - name: {{ .Values.fluentd_service.servicedataPVCName }}-logs
          emptyDir: {}
        - name: fluentdconfig-map
          projected:
            sources:
            - configMap:
                name: {{ .Values.serviceName }}-fluentd-configmap
        {{- end }}
        {{- if eq .Values.timeZone.enable true }}
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
        {{- end }}
