{{- if .Values.fluentdConf.enable }}
# Create the configmap when fluentd is enabled
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-fluentd-configmap
data:
  fluentd.conf: |
    <source>
        @type forward
        @id input_forward
        port {{ .Values.fluentdConf.TCPPort | default 24224 }}
        bind 0.0.0.0
    </source>
    <source>
        @type http
        @id input_http
        port {{ .Values.fluentdConf.RESTPort | default 8888 }}
    </source>
    <source>
        @type debug_agent
        @id input_debug_agent
        bind 127.0.0.1
        port 24230
    </source>
    <source>
        @type udp
        tag DCTMEventHub.events # required
        port {{ .Values.fluentdConf.UDPPort | default 20001 }}
        bind 0.0.0.0
        <parse>
            @type json
        </parse>
    </source>
    <match *.**>
        @type kafka2
        sasl_over_ssl false
        use_event_time true
{{- if eq .Values.fluentdConf.bufferingMode "FILEBUFFER" }}
        <buffer {{ .Values.fluentdConf.kafkaTopic }}>
            @type file
            path /var/log/td-agent/buffer/td
            flush_interval {{ .Values.fluentdConf.flushInterval | default "3s" }}
            flush_thread_count {{ .Values.fluentdConf.flushThreadCount | default "4" }}
        </buffer>
{{ else }}
        <buffer {{ .Values.fluentdConf.kafkaTopic }}>
            @type memory
        </buffer>
{{- end }}
        <format>
            @type json
        </format>
        brokers {{ template "generatekfklist" .Values }}
        scram_mechanism sha512
        username {{ .Values.fluentdConf.kafkaUser }}
        password {{ .Values.fluentdConf.kafkaUsrPasswd }}
        topic_key {{ .Values.fluentdConf.kafkaTopic }}
        topic {{ .Values.fluentdConf.kafkaTopic }}
        required_acks -1
        compression_codec {{ .Values.fluentdConf.compressionMode | default "nil" }}
    </match>
{{- end }}