content-server:
     extraInitContainers:
     - name: ccsmartview-dar-installer
       image: artifactory.otxlab.net/bpdockerhub/dctm-smartviewm365:23.4
       imagePullPolicy: Always
       volumeMounts:
       - name: dcs-data-pvc
         mountPath: /opt/dctm_docker/customscriptpvc 
         subPath: initcontainercustomscripts/<sname>dcs-pg