content-server:
     extraInitContainers:
     - name: dctm-records-darinstallation
       image: artifactory.otxlab.net/bpdockerhub/dctm-records-darinstallation:23.4
       imagePullPolicy: Always
       volumeMounts:
       - name: dcs-data-pvc
         mountPath: /opt/dctm_docker/customscriptpvc 
         subPath: initcontainercustomscripts/<sname>dcs-pg
