{{- if .Values.deploySecretsFromHelm -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}-secret
  labels: {{ include "appworks-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if hasKey .Values "database" }}
  AWG_DB_PASSWORD: {{ .Values.database.appworksdb.password | b64enc }}
  {{- else }}
  AWG_DB_PASSWORD: {{ .Values.postgres.appworksdb.password | b64enc }}
  {{- end }}
  {{- if hasKey .Values.awg.settings.mail "smtpPassword" }}
  AWG_OTAG_SMTP_PASSWORD: {{ .Values.awg.settings.mail.smtpPassword | b64enc  }}
  {{- end }}
  {{- if hasKey .Values.awg.settings.mail "oauthClientSecret" }}
  AWG_OTAG_OAUTH_CLIENT_SECRET: {{ .Values.awg.settings.mail.oauthClientSecret | b64enc  }}
  {{- end }}
  {{- if and (hasKey .Values.newrelic "licenseKey") (eq .Values.newrelic.enabled true) }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.newrelic.licenseKey | b64enc }}
  {{- end }}
  {{- end }}
