{{- if and (.Values.deploySecretsFromHelm) ( hasKey .Values.image "pgInitContainer") }}
apiVersion: v1
kind: Secret
metadata:
  name: awg-pg-init-container-secret
  labels: {{ include "appworks-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  # https://www.postgresql.org/docs/12/libpq-pgpass.html
  {{- if hasKey .Values "database" }}
  PGPASSWORD: {{ (printf "%s%s" "*:*:*:*:" .Values.database.admin.password) | b64enc }}
  PGNEWPASSWORD: {{ .Values.database.appworksdb.password | b64enc }}
  {{- else}}
  PGPASSWORD: {{ (printf "%s%s" "*:*:*:*:" .Values.postgres.admin.password) | b64enc }}
  PGNEWPASSWORD: {{ .Values.postgres.appworksdb.password | b64enc }}
  {{- end}}
{{- end }}
