apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.pvcName }}  
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}