# This secret is created to use in htpps openshift route.
{{ if eq .Values.openshifttls.enable true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}{{ "-tls" }} 
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tlscrt }}
  tls.key: {{ .Values.ingress.tlskey }}
{{ end }}