apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-appproperties-configmap
  namespace: {{ .Values.namespace }}
data:
  app.properties: |
   {{- range .Values.wdkAppXmlConfig.tagsnvalues }}
   {{ . }}
   {{- end }}
   {{- if eq .Values.otds.enable true }}
   application.authentication.otds_sso.enabled=true
   application.authentication.otds_sso.repo_selection_page_required={{ .Values.otds.authentication.repoSelectionPageRequired }}
   application.authentication.otds_sso.dm_login_ticket_timeout={{ .Values.otds.authentication.loginTicketTimeout }}
   application.authentication.otds_sso.renew_token_after_logout={{ .Values.otds.authentication.renewtokenafterlogout}}
   {{ end }}
   {{- if eq .Values.otds.authentication.useDefaultDocbase true }}
   {{- if .Values.containers.records.docbaseName }}
   application.authentication.docbase={{ .Values.containers.records.docbaseName }}
   {{ end }}
   {{ end }}