{{- if eq .Values.otds.enable true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-otdsproperties-configmap
  namespace: {{ .Values.namespace }}
data:
  otdsoauth.properties: |
   otds_url={{ .Values.otds.url }}
   client_id={{ .Values.otds.clientID }}
   scheme= {{ .Values.otds.scheme }}
{{ end }}