{{- if eq .Values.ingress.tls.enable true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Values.namespace}}
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: {{ .Values.certificatesecret.crt }}
  tls.key: {{ .Values.certificatesecret.key }}
{{ end }}