  # This secret is used for CC, DB

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace}}
type: {{ .Values.secret.type }}
stringData :
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote}}