apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
type: Opaque
data:
  tomcatPassword: {{ default "" .Values.tomcat.password | b64enc | quote }}
  globalRegistryPassword: {{ default "" .Values.dfc.globalRegistryPassword | b64enc | quote }}
  newrelicLicensekey: {{ default "" .Values.newrelic.license_key | b64enc | quote }}
  dfcTrustStorePassword: {{ default "" .Values.certificate.dfcTrustStorePassword | b64enc | quote }}
  installOwner: {{ default "" .Values.installOwner | b64enc | quote }}