#Replica count
replicaCount: 1
#volumeClaimTemplates details
volumeClaimTemplates:
  size: 200Mi
#resources
resources:
  limits:
    cpu: 8000m
    memory: 32Gi
  requests:
    cpu: 4000m
    memory: 16Gi