# Default values for d2classic
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

### Environment ###
env:
  # Only used in cloud tenant environment to add subscriptionName query string 
  # parameter to the OTDS authentication URL when redirecting the user.
  #subscriptionName: subscription1
  tomcatJVMArgs: ""
  webappName: &webappName D2
  # By Default the appTitle is D2 that gets displayed on the Browser tab.
  # Update to a custom appTitle below when required 
  appTitle: 
  domain: 

## serviceAnnotations define custom annotations that need to be assigned to d2classic service.
## For example:
##  cloud.google.com/backend-config: '{"ports": {"80": "abcd-d2classic-backend"}}'
##  cloud.google.com/neg: '{"ingress": true}'
serviceAnnotations: {}

serviceAccount: 
  createserviceaccount: true
  serviceAccountName: documentum-sa

### Tomcat ###  
tomcat:
  catalinaHome: /opt/tomcat
  connectionTimeoutInMilliseconds: 900000
  maxHttpHeaderSize: 100000
  logfilerotation: 7  #Log files are rotated "logfilerotation" times before being removed 
  logfilesize: 5M  #Log files are rotated only if they grow bigger then "logfilesize" bytes
  logrotateFrequency: 1d  #Log files are rotated every "logrotateFrequency". Ex., 10m, 10h, 10d

### Docbroker ###

docbroker:
  count: 2
  serviceName: dbr
  port: 1489

cs:
  custom:
    scriptinPVC: true
    ##In the case of  hybrid installers approach, volumeMountName value should be custom-script-pvc and scriptPVCname value should be shared-pvc
    volumeMountName: dcs-data-pvc
    scriptPVCname: dcs-pg-pvc
    PVCSubPath: initcontainercustomscripts/dcs-pg

methodsvr:
  containerName: dcs-pg

session:
  allowTrustedLogin: false

### Docbase ###
docbase:
  name: docbase1
# if k8s version is < 1.19  default initial delay is set to 250 seconds and 60 seconds if k8s version is >= 1.19
# Increase the initialDelaySeconds and add the value below if default value is not enough
readinessProbe:
  initialDelaySeconds: 
# if k8s version is < 1.19  default initial delay is set to 250 seconds and 60 seconds if k8s version is >= 1.19
# Increase the initialDelaySeconds and add the value below if default value is not enough
livenessProbe:
  initialDelaySeconds: 
  
startupProbe:
  initialDelaySeconds: 180  
  
replicaCount: 2

fsGroup: 1000

images:
  repository : artifactory.otxlab.net/bpdockerhub
  name : common/oraclelinux-openjdk-tomcat
  tag : "dctm-oraclelinux9-openjdk17.0.6-tomcat9.0.71"
  pullPolicy: IfNotPresent
  pullSecrets:

extensionImage:
  repository: artifactory.otxlab.net/bpdockerhub
  name : dctm-d2pp-classic
  tag : 23.2.0
  pullPolicy: Always
 
extraInitContainers: []
### Secret ###
secret:
  csConfigName: cs-secret-config

### extra Environment Variables ###
extraEnv:
  
nameOverride: ""
fullnameOverride: ""

### Persistent Volume ###
persistentVolume:
  vctAccessModes: ReadWriteOnce
  storageClass: trident-nfs
  size: 1Gi

certificate:
  use_certificate: false
  dbrserviceName: dbr

dbrpersistentVolume:
  dbrdataPVCName: certdbr-data-pvc

### Graylog Enabled by default, set to false if logs mount to PVC ###
graylog:
  enable: true
  volumeClaimTemplate:
    logVctAccessModes: ReadWriteOnce
    logVctSize: 2Gi
    logVctStorageClass: trident-nfs

serviceType: ClusterIP
  
### d2report Configuration ###
d2report:
  enable: false
  dctm_reports_iis_host: dctm-ingress.d2.cfcr-lab.bp-paas.otxlab.net
  d2_host: d2-ingress.d2.cfcr-lab.bp-paas.otxlab.net
  dctm_reports_port: "443"
  d2_port: "443"
  d2_scheme: "https:"
  dctm_reports_scheme: "https"
### D2Classic Extension image ###
extension:  
  createPVC: true
  PVCAccessMode: ReadWriteMany
  PVCStorageClass: trident-nfs
  PVCSize: 4Gi
  pvcName: d2-extension-pvc
  #Update the below parameters in case of Static Provisioning in AWS
  staticPVName:
  reclaimPolicy:
  awsEFSCSIDriver: efs.csi.aws.com
  awsEFSCSIHandle:
### Custom Configuration ###
customConfigurations:
  custom: false
  hook_approach: false
  createPVC: false
  scriptPVCname: d2custom-shared-pvc
  persistentVolume:
    awsEFS: false
    awsEFSCSIDriver: efs.csi.aws.com
    awsEFSCSIHandle:
    existVolumePv:
    reclaimPolicy: Retain
    storageClass: trident-nfs
    size: 2Gi
  locale: 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

###############################################################
#  BEGIN parameter value definitions for D2 configuration files
###############################################################

# directory in chart holding any .properties config file "coda" files.
# These files are appended to the corresponding default .properties config
# file in the resulting config map definition.  This provides a convenient
# way for solutions built on top of D2 to override settings in D2FS.properties,
# settings.properties etc.
configFileOverrideFilesDir: configFileOverrideFiles

# parameters used to compose d2classic-shiro-ini config map
shiro:
   # Set this to false if no SSO will be used
   enable: true
   # SSOType may be OTDS or SAML:  provide required values in the relevant section below accordingly
   SSOType: OTDS
   OTDS:
      clientId: d2_oauth_client
      apiSvc: http://otdsws:80/otdsws
      # The Ingress URL for the OTDS Authentication service
      authSvcProtocol: https
      authSvc: d2-ingress.d2.cfcr-lab.bp-paas.otxlab.net/otdsws
      appName: Documentum D2 CE 23.4
            
   SAML:
      idpUrl: SPECIFY_ME_shiro.SAML.idpUrl
      assertionConsumerServiceUrl: SPECIFY_ME_shiro.SAML.assertionConsumerServiceUrl
      logoutResponseEndpointUrl: SPECIFY_ME_shiro.SAML.logoutResponseEndpointUrl
      issuer: SPECIFY_ME_shiro.SAML.issuer
      idpTokenSigningCertificate: SPECIFY_ME_shiro.SAML.idpTokenSigningCertificate
      jksLocation: SPECIFY_ME_shiro.SAML.jksLocation
      serviceProviderIdentifier: SPECIFY_ME_shiro.SAML.serviceProviderIdentifier

# parameters used to compose d2classic-d2fs-properties config map
#D2FS:
#   propertyPageConstraintValidation: true
#   loadBalancedContentServer: false

# parameters used to compose d2classic-settings-properties config map
settings:   
   # "connection.remote.url" setting in "settings.properties"
   # When using Ingress to expose webapp service inside the cluster to the outside user, 
   # the ingress is behaving like the reverse proxy. The connectionRemoteUrl should be the 
   # set to the URL of the Ingress resource that the outside user uses to access the 
   # webapp inside the cluster.
   connectionRemoteUrlProtocol: https
   connectionRemoteUrl: 
   - d2-ingress.d2.cfcr-lab.bp-paas.otxlab.net/
   - *webappName
   browserPluginMode: thin
   allowedFrameOrigins: 

# parameters used to compose d2classic-ESAPI-properties config map 
esapi:  
    forcedSecureCookies: 

# parameters used to compose d2classic-ctfconfig-json config map
#ctfConfig:
#   version: 20.2.0000.092

# parameters used to compose d2classic-logback-xml config map
logback:
   file: 
   - /opt/tomcat/webapps/
   - *webappName
   - /logs/D2.log
   fileNamePattern: 
   - /opt/tomcat/webapps/
   - *webappName
   - /logs/D2-%d{yyyy-MM-dd}.log.zip
   logLevel: info

# parameters used to compose d2classic-log4j-properties config map
log4j:
   file: 
   - /opt/tomcat/webapps/
   - *webappName
   - /logs
   logLevel: WARN

#############################################################
#  END parameter value definitions for D2 configuration files
#############################################################

### New Relic Configuration ###

newrelic:
  enable: false
  app_name: DOCUMENTUM_D2CLIENT-PROD-OT2_CFCR_BP2-ECD
  proxy_host: 
  proxy_port: 

smtp:
  hostname:
  port: 25
  from:
  auth: false
  starttls:
    enable: false
  socketFactory:
    port:
    class: javax.net.ssl.SSLSocketFactory
    fallback: false

bravatls:
  enable: false
  certName:
