{{- if .Values.bpm.log4j.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.bpm_configMap_name }}
data:
  log4j: |
    #------------------- Log4j2 internals  --------------------------
    #The level of internal Log4j events that should be logged to the console.
    # Valid values for this attribute are "trace", "debug", "info", "warn",
    # "error" and "fatal"
    status = error
    #Either "err" for stderr, "out" for stdout, a file path, or a URL.
    dest = err
    #The name of the configuration.
    name = BPMPropertiesConfig
    monitorInterval = 5
    
    rootLogger.level= {{ .Values.bpm.log4j.rootLogLevel }}
    rootLogger.appenderRefs = A1,F1
    rootLogger.appenderRef.A1.ref = STDOUT
    rootLogger.appenderRef.F1.ref = File
    
    #------------------- CONSOLE --------------------------
    appender.A1.type = Console
    appender.A1.name = STDOUT
    appender.A1.filter.threshold.type = ThresholdFilter
    appender.A1.filter.threshold.level = ERROR
    appender.A1.layout.type = PatternLayout
    appender.A1.layout.pattern = %d{ISO8601} %5p [%t] [%c] - %m%n
    
    #------------------- FILE --------------------------
    appender.F1.type = RollingFile
    appender.F1.name = File
    appender.F1.fileName = /opt/dctm/{{ .Values.jmsVersion }}/logs/bpm.log
    appender.F1.filePattern = /opt/dctm/{{ .Values.jmsVersion }}/logs/bpm-%d{MM-dd-yy-HH-mm-ss}-%i.log
    appender.F1.layout.type = PatternLayout
    appender.F1.layout.pattern = %d{ISO8601} %5p [%t] [%c] - %m%n
    appender.F1.policies.type = Policies
    appender.F1.policies.size.type = SizeBasedTriggeringPolicy
    appender.F1.policies.size.size = 10MB
    appender.F1.strategy.type = DefaultRolloverStrategy
    appender.F1.strategy.max = 10
    
    #------------------- BPM --------------------------
    appender.bpm.type = RollingFile
    appender.bpm.name = bpm
    appender.bpm.fileName = /opt/dctm/{{ .Values.jmsVersion }}/logs/bpm-runtime.log
    appender.bpm.filePattern = /opt/dctm/{{ .Values.jmsVersion }}/logs/bpm-runtime-%d{MM-dd-yy-HH-mm-ss}-%i.log
    appender.bpm.layout.type = PatternLayout
    appender.bpm.layout.pattern = %d{ISO8601} %5p [%t] [%c] - %m%n
    appender.bpm.policies.type = Policies
    appender.bpm.policies.size.type = SizeBasedTriggeringPolicy
    appender.bpm.policies.size.size = 1MB
    appender.bpm.strategy.type = DefaultRolloverStrategy
    appender.bpm.strategy.max = 10
    
    logger.bpm.name = com.documentum.bpm
    logger.bpm.level = {{ .Values.bpm.log4j.bpmLogLevel }}
    logger.bpm.additivity = false
    logger.bpm.appenderRef.bpm.ref = bpm
    
    logger.bps.name = com.documentum.bps
    logger.bps.level = {{ .Values.bpm.log4j.bpsLogLevel }}
    logger.bps.additivity = false
    logger.bps.appenderRef.bpm.ref = bpm
    #------------------- FILE_TRACE --------------------------
    
    appender.FILE_TRACE.type = RollingFile
    appender.FILE_TRACE.name = FILE_TRACE
    appender.FILE_TRACE.fileName = /opt/dctm/{{ .Values.jmsVersion }}/logs/bpm_trace.log
    appender.FILE_TRACE.filePattern = /opt/dctm/{{ .Values.jmsVersion }}/logs/bpm_trace-%d{MM-dd-yy-HH-mm-ss}-%i.log
    appender.FILE_TRACE.layout.type = PatternLayout
    appender.FILE_TRACE.layout.pattern= %d{ISO8601} %5p [%t] [%c] - %m%n
    appender.FILE_TRACE.policies.type = Policies
    appender.FILE_TRACE.policies.size.type = SizeBasedTriggeringPolicy
    appender.FILE_TRACE.policies.size.size=100MB
    appender.FILE_TRACE.strategy.type = DefaultRolloverStrategy
    appender.FILE_TRACE.strategy.max = 10
    
    logger.FILE_TRACE.name = tracing
    logger.FILE_TRACE.level = {{ .Values.bpm.log4j.traceLogLevel }}
    logger.FILE_TRACE.additivity = false
    logger.FILE_TRACE.appenderRef.FILE_TRACE.ref = FILE_TRACE
{{- end }}    