apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.saml_configMap_name }}  
data:
  log4j: |
    rootLogger.level={{ .Values.saml.log4j.rootLogLevel }}
    rootLogger.appenderRefs = A1, F1
    rootLogger.appenderRef.A1.ref = STDOUT
    rootLogger.appenderRef.F1.ref = File
    property.filename = /opt/dctm/{{ .Values.jmsVersion }}/logs
    monitorInterval = 5
    
    #------------------- SAML ------------------------
    appender.SAML.type=RollingFile
    appender.SAML.name=File
    appender.SAML.filePattern=${filename}/SAMLAuthentication.log.%i.%d{yyyy-MM-dd}
    appender.SAML.layout.type=PatternLayout
    appender.SAML.fileName=${filename}/SAMLAuthentication.log
    appender.SAML.layout.pattern=%d{ABSOLUTE} %5p [%t] %c - %m%n
    appender.SAML.policies.type=Policies
    appender.SAML.policies.time.type=TimeBasedTriggeringPolicy
    appender.SAML.policies.time.interval=1
    appender.SAML.policies.time.modulate=true
    appender.SAML.policies.size.type=SizeBasedTriggeringPolicy
    appender.SAML.policies.size.size=100MB
    appender.SAML.strategy.type=DefaultRolloverStrategy
    appender.SAML.strategy.max=5